fix: check guest permissions from config correctly
mattermost/mattermost-plugin-bulk-invite pull request #24
Opened 2023-12-07 15:38 UTC by fmartingr

#### Summary

Properly check permissions if the user running the bulk invite wants to invite guests from other teams to the channel the same way Mattermost's does.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-55584

2023-12-08 15:53 UTC, esarafianou requested changes
@fmartingr while this relaxes the existing implementation, there's a case it doesn't cover: having in the file some members that are from another team (thus the "addToTeam" config), and having guests (thus the "addGuests" config from the same team. In this case, everyone should be bulk invited but with this implementation, the bulk invite will fail. 
That's because the permissions are applied only to the requesting user without looking at each user-to-be-invited separately. I think that shouldn't be the case, but in the end, that's a product decision whether we'll make the bulk-invite plugin more strict than the normal invite functionality.

2023-12-11 10:17 UTC, fmartingr commented
> @fmartingr while this relaxes the existing implementation, there's a case it doesn't cover: having in the file some members that are from another team (thus the "addToTeam" config), and having guests (thus the "addGuests" config from the same team. In this case, everyone should be bulk invited but with this implementation, the bulk invite will fail.
> 
> That's because the permissions are applied only to the requesting user without looking at each user-to-be-invited separately. I think that shouldn't be the case, but in the end, that's a product decision whether we'll make the bulk-invite plugin more strict than the normal invite functionality.

The problem with that is that we want to provide feedback early, and depending on the users in the file we can not process them directly in the submit request because it would timeout. 

I will consult this with the team. Maybe adding a new "add guests from other teams" ? or just disallow that option directly, I don't know if we have a requirement for that either way.

From the security side of thing, is this good to go?

2023-12-12 09:12 UTC, fmartingr commented
We ended up deciding disabling guests for now, since it wasn't part of the request. We will think about this when is a proper requirement. Thank you for the reviews.

2023-12-12 12:17 UTC, esarafianou approved these changes

2023-12-13 09:00 UTC, merged